# Generated by Django 2.2.17 on 2021-04-03 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneWordStory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='name',
            new_name='title',
        ),
    ]
