# Generated by Django 2.2.17 on 2021-04-03 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oneWordStory', '0002_auto_20210403_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='url',
        ),
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oneWordStory.UserProfile'),
            preserve_default=False,
        ),
    ]
