# Generated by Django 2.2.17 on 2021-04-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneWordStory', '0003_auto_20210403_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'Stories'},
        ),
        migrations.RenameField(
            model_name='word',
            old_name='user',
            new_name='userProfile',
        ),
        migrations.AddField(
            model_name='story',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contributions',
            field=models.ManyToManyField(to='oneWordStory.Story'),
        ),
    ]
