# Generated by Django 2.2.17 on 2021-04-06 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oneWordStory', '0004_auto_20210404_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='lastUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oneWordStory.UserProfile'),
        ),
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='oneWordStory.UserProfile'),
        ),
    ]
